# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: backend
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: backend
#   template:
#     metadata:
#       labels:
#         app: backend
#     spec:
#       containers:
#       - name: backend
#         image: ramrodwal/server:latest
#         ports:
#         - containerPort: 5000
#         # volumeMounts:
#         # - name: logs
#         #   mountPath: /app/logs
#         resources:
#           limits:
#             cpu: "1"
#             memory: "1Gi"
#           requests:
#             cpu: "0.5"
#             memory: "500Mi"
#       # volumes:
#       # - name: logs
#       #   hostPath:
#       #     path: /var/logs/Backendlogs
#       #     type: Directory


apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ramrodwal/server:latest
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: logs
          mountPath: /usr/src/app/logs
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "0.5"
            memory: "500Mi"
      volumes:
      - name: logs
        hostPath:
          path: /home/ram/Documents/SPE_MajorProject_CouchPotato/mernapp/Logfile.log
          type: Directory

