apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
  - name: http
    protocol: TCP
    port: 90
    targetPort: 5000
    
  # cors:
  #   # - maxAgeSeconds: 3600
  #   - allowedOrigins:
  #       - http://192.168.49.2:32292/


  type: NodePort