version: '3'
services:
  api-server:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - mern-app
    container_name: node-app
    command: npm start
  react-app:
    image: temp
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - mern-app
    command: npm start
networks:
  mern-app:
    driver: bridge
